//tealium universal tag - utag.111 ut4.0.201806120503, Copyright 2018 Tealium.com Inc. All Rights Reserved.
!function(t){"use strict";function e(t){return!isNaN(parseFloat(t))&&isFinite(t)}t.timing=t.timing||{getTimes:function(i){var n=t.performance||t.webkitPerformance||t.msPerformance||t.mozPerformance;if(void 0===n)return!1;var o=n.timing,r={};if(i=i||{},o){if(i&&!i.simple)for(var a in o)e(o[a])&&(r[a]=parseFloat(o[a]));if(void 0===r.firstPaint){var m=0;t.chrome&&t.chrome.loadTimes?(m=1e3*t.chrome.loadTimes().firstPaintTime,r.firstPaintTime=m-o.navigationStart):"number"==typeof o.msFirstPaint&&(m=o.msFirstPaint,r.firstPaintTime=m-o.navigationStart),i&&!i.simple&&(r.firstPaint=m)}r.loadTime=o.loadEventEnd-o.fetchStart,r.domReadyTime=o.domComplete-o.domInteractive,r.readyStart=o.fetchStart-o.navigationStart,r.redirectTime=o.redirectEnd-o.redirectStart,r.appcacheTime=o.domainLookupStart-o.fetchStart,r.unloadEventTime=o.unloadEventEnd-o.unloadEventStart,r.lookupDomainTime=o.domainLookupEnd-o.domainLookupStart,r.connectTime=o.connectEnd-o.connectStart,r.requestTime=o.responseEnd-o.requestStart,r.initDomTreeTime=o.domInteractive-o.responseEnd,r.loadEventTime=o.loadEventEnd-o.loadEventStart}return r},printTable:function(t){var e={},i=this.getTimes(t)||{};Object.keys(i).sort().forEach(function(t){e[t]={ms:i[t],s:+(i[t]/1e3).toFixed(2)}}),console.table(e)},printSimpleTable:function(){this.printTable({simple:!0})}},"undefined"!=typeof module&&module.exports&&(module.exports=t.timing)}("undefined"!=typeof window?window:{});var isClient='undefined'!=typeof window,isLocalStorageSP=function(){try{return window.localStorage.setItem('testKey',1),window.localStorage.removeItem('testKey'),!0}catch(a){return!1}},Storage={getItem:function getItem(){},setItem:function setItem(){},removeItem:function removeItem(){}};isClient&&isLocalStorageSP()&&(Storage.getItem=function(a){return window.localStorage.getItem(a)},Storage.setItem=function(a,b){return window.localStorage.setItem(a,b)},Storage.removeItem=function(a){return window.localStorage.removeItem(a)});function getRandomInt(min,max){return Math.floor(Math.random()*(max-min+1)+min);}
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"dom.domain":"domain","$page[name]":"page_name","$timing[chance]":"chanceLoad","$timing[pixelUrl]":"pixelUrl"};u.extend=[function(a,b){try{if(1){var domain=b["dom.domain"];b['$timing[chance]']=0;b['$timing[pixelUrl]']="https://vulcan.chotot.org/beacon";if(b['ut.env']==='prod'){b['$timing[pixelUrl]']="https://vulcan.chotot.com/beacon";}
if(["nha.chotot.org","nha.chotot.com"].indexOf(domain)>-1){b['$timing[chance]']=10;}
if(['dev','qa'].indexOf(b['ut.env'])>-1){console.debug('Timing performance EXT',b);}
return b;}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"pixelUrl":"https://vulcan.chotot.org/beacon","domain":"","page_name":"","chanceLoad":0,};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(!u.initialized){if(Storage.getItem("performanceTiming")==="true"){}else{var performanceTiming=getRandomInt(1,100);performanceTiming=(performanceTiming<=u.data.chanceLoad)
Storage.setItem("performanceTiming",performanceTiming)}
var performanceTiming=Storage.getItem("performanceTiming");if(performanceTiming==="true"){var timing_metric=timing.getTimes();timing_metric.domain=u.data.domain;timing_metric.page_name=u.data.page_name;if(timing_metric.page_name){u.loader({"type":"img","src":u.data.pixelUrl+'?'+utag.serialize(timing_metric)});u.initialized=true;}}
}
}};utag.o[loader].loader.LOAD(id);})("111","chotot.chotot");}catch(error){utag.DB(error);}
