//tealium universal tag - utag.38 ut4.0.201803130348, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.map={"gtmData":"gtmData","$page[platform]":"platform","$ad[list_id]":"list_id"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//www.googletagmanager.com/gtm.js?","cid":"GTM-NJQRRH","dl":"dataLayer"};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(u.data.dl===""){u.data.dl="dataLayer";}
if(typeof window[u.data.dl]==='undefined'){window[u.data.dl]=window[u.data.dl]||[];window[u.data.dl].push({'gtm.start':new Date().getTime(),event:'gtm.js'});c.push("id"+u.data.kvp_delim+u.data.cid);c.push("l"+u.data.kvp_delim+u.data.dl);}
if(u.data['platform']){u.data.gtmData['platform']=u.data['platform'];}
if(u.data['list_id']){u.data.gtmData['list_id']=u.data['list_id'];}
c.push(u.data.gtmData);if(u.data.gtmData!=undefined)
window[u.data.dl].push(u.data.gtmData);if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url+c.join(u.data.qsp_delim),"loc":"script","id":"utag_38"});}
}};utag.o[loader].loader.LOAD(id);}("38","chotot.chotot"));}catch(error){utag.DB(error);}
