//tealium universal tag - utag.39 ut4.0.201810111022, Copyright 2018 Tealium.com Inc. All Rights Reserved.
var appboy=appboy||{};for(var s="destroy toggleAppboyLogging setLogger openSession changeUser requestImmediateDataFlush requestFeedRefresh subscribeToFeedUpdates logCardImpressions logCardClick logFeedDisplayed requestInAppMessageRefresh logInAppMessageImpression logInAppMessageClick logInAppMessageButtonClick subscribeToNewInAppMessages removeSubscription removeAllSubscriptions logCustomEvent logPurchase isPushSupported isPushBlocked isPushGranted isPushPermissionGranted registerAppboyPushMessages unregisterAppboyPushMessages submitFeedback ab ab.User ab.User.Genders ab.User.NotificationSubscriptionTypes ab.User.prototype.getUserId ab.User.prototype.setFirstName ab.User.prototype.setLastName ab.User.prototype.setEmail ab.User.prototype.setGender ab.User.prototype.setDateOfBirth ab.User.prototype.setCountry ab.User.prototype.setHomeCity ab.User.prototype.setEmailNotificationSubscriptionType ab.User.prototype.setPushNotificationSubscriptionType ab.User.prototype.setPhoneNumber ab.User.prototype.setAvatarImageUrl ab.User.prototype.setLastKnownLocation ab.User.prototype.setUserAttribute ab.User.prototype.setCustomUserAttribute ab.User.prototype.addToCustomAttributeArray ab.User.prototype.removeFromCustomAttributeArray ab.User.prototype.incrementCustomUserAttribute ab.InAppMessage ab.InAppMessage.SlideFrom ab.InAppMessage.ClickAction ab.InAppMessage.DismissType ab.InAppMessage.OpenTarget ab.InAppMessage.ImageStyle ab.InAppMessage.Orientation ab.InAppMessage.CropType ab.InAppMessage.prototype.subscribeToClickedEvent ab.InAppMessage.prototype.subscribeToDismissedEvent ab.InAppMessage.prototype.removeSubscription ab.InAppMessage.prototype.removeAllSubscriptions ab.InAppMessage.Button ab.InAppMessage.Button.prototype.subscribeToClickedEvent ab.InAppMessage.Button.prototype.removeSubscription ab.InAppMessage.Button.prototype.removeAllSubscriptions ab.SlideUpMessage ab.ModalMessage ab.FullScreenMessage ab.ControlMessage ab.Feed ab.Feed.prototype.getUnreadCardCount ab.Card ab.ClassicCard ab.CaptionedImage ab.Banner ab.WindowUtils display display.automaticallyShowNewInAppMessages display.showInAppMessage display.showFeed display.destroyFeed display.toggleFeed sharedLib".split(" "),i=0;i<s.length;i++){for(var k=appboy,l=s[i].split("."),j=0;j<l.length-1;j++)k=k[l[j]];k[l[j]]=function(){console&&console.error("The Appboy SDK has not yet been loaded.")}}appboy.initialize=function(){console&&console.error("Appboy cannot be loaded - this is usually due to strict corporate firewalls or ad blockers.")};appboy.getUser=function(){return new appboy.ab.User};appboy.getCachedFeed=function(){return new appboy.ab.Feed};function InAppRegister(){appboy.subscribeToNewInAppMessages(function(inAppMessages){var message=inAppMessages[0];if(message!=null){var msgId=message.extras["msg-id"];var shouldDisplayMessage=true;if(msgId=="push-primer"){if(!appboy.isPushSupported()||appboy.isPushPermissionGranted()||appboy.isPushBlocked()){shouldDisplayMessage=false;}
message.buttons[0].subscribeToClickedEvent(function(){appboy.registerAppboyPushMessages();});}
if(shouldDisplayMessage){appboy.display.showInAppMessage(message);}}
return inAppMessages.slice(1);});}
appboy.loadCss=function(filename){var fileref=document.createElement("link")
fileref.setAttribute("rel","stylesheet")
fileref.setAttribute("type","text/css")
fileref.setAttribute("href",filename)
if(typeof fileref!="undefined")
document.getElementsByTagName("head")[0].appendChild(fileref)}
appboy.loadCss("//js.appboycdn.com/web-sdk/1.6/appboy.min.css");try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<35){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];if(utag.ut.isEmptyObject===undefined){u.isEmptyObject=function(o,a){for(a in o){if(utag.ut.hasOwn(o,a)){return false;}}return true;};}else{u.isEmptyObject=utag.ut.isEmptyObject;}
u.map={"$user[account_id]":"customer_id","$user[full_name]":"user.setFirstName","$appboy[pushPrimer]":"custom_event_name","$user[email]":"user.setEmail","$user[fingerprint]":"fingerprint"};u.extend=[function(a,b){try{if(typeof b['$user[account_id]']!='undefined'){b['$appboy[customer_id]']=b['$user[account_id]']}}catch(e){utag.DB(e)}},function(a,b,c,d){try{if(1){c=[b['$appboy[userCustomLabel]'],b['$appboy[userCustomValue]'],b['$appboy[userCustomRegionLabel]'],b['$ad[region]']];for(d=0;d<c.length;d++){if(typeof c[d]=='undefined'||c[d]=='')c[d]='empty_value'};b['$appboy[userCustomData]']=c.join(':')}}catch(e){utag.DB(e)}},function(a,b){try{if(b['$page[referrer]'].toString().indexOf('dangtin/xemlai')>-1){b['$appboy[pushPrimer]']='prime-for-push'}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:39");utag.DB(b);var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//js.appboycdn.com/web-sdk/2.2/appboy.min.js","api_key":'3f482ca8-a60e-4fbf-8f13-cec3acdede1a',"user":{},"custom_event_name":"","custom_event_properties":{},"purchase_properties":{},"product_id":[],"product_quantity":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB("send:39:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("user.")===0){u.data.user[e[f].substr(5)]=b[d];}else if(e[f].indexOf("custom_event_properties.")===0){u.data.custom_event_properties[e[f].substr(24)]=b[d];}else if(e[f].indexOf("purchase_properties.")===0){u.data.purchase_properties[e[f].substr(20)]=b[d];}else{u.data[e[f]]=b[d];}}}}
utag.DB("send:39:MAPPINGS");utag.DB(u.data);u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"USD";u.data.customer_id=u.data.customer_id||b._ccustid||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
u.data.product_quantity[0]=u.data.product_quantity[0]||1;if(!u.data.api_key){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
u.loader_cb=function(a,b,c){utag.DB("send:39:CALLBACK");if(['dev','qa'].indexOf(b['ut.env'])>-1){console.log('appboy called loader_cb');}
if(!u.initialized){if(['dev','qa'].indexOf(b['ut.env'])>-1){console.log('appboy called init');}}
appboy.initialize(u.data.api_key,{sessionTimeoutInSeconds:900,enableHtmlInAppMessages:true,safariWebsitePushId:'web.chotot.com',enableLogging:false,noCookies:true});if(!u.inappregister){InAppRegister()
u.inappregister=true}
if(u.data.customer_id&&(u.data.customer_id!="0")){appboy.changeUser(u.data.customer_id);}else{appboy.changeUser(u.data.fingerprint);}
appboy.openSession();if(u.data.order_id){if(!u.isEmptyObject(u.data.purchase_properties)){appboy.logPurchase(u.data.product_id[0],u.data.order_subtotal,u.data.order_currency,u.data.product_quantity[0],u.data.purchase_properties);}else{appboy.logPurchase(u.data.product_id[0],u.data.order_subtotal,u.data.order_currency,u.data.product_quantity[0]);}}
if(u.data.custom_event_name){if(!u.isEmptyObject(u.data.custom_event_properties)){appboy.logCustomEvent(u.data.custom_event_name,u.data.custom_event_properties);}else{appboy.logCustomEvent(u.data.custom_event_name);}}
var appboyUser=appboy.getUser();var twoArgsFunc=["setCustomUserAttribute"];for(var funcName in u.data.user){if(appboyUser[funcName]!==undefined){if(twoArgsFunc.indexOf(funcName)>-1){var[arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8]=u.data.user[funcName].split(":");if(arg1!==undefined)
arg1=arg1.trim();if(arg2!==undefined)
arg2=arg2.trim();if(arg3!==undefined)
arg3=arg3.trim();if(arg4!==undefined)
arg4=arg4.trim();if(arg5!==undefined)
arg5=arg5.trim();if(arg6!==undefined)
arg6=arg6.trim();if(arg7!==undefined)
arg7=arg7.trim();if(arg8!==undefined)
arg8=arg8.trim();if(arg1!==undefined&&arg2!==undefined)
appboyUser[funcName](arg1,arg2);if(arg3!==undefined&&arg4!==undefined)
appboyUser[funcName](arg3,arg4);if(arg5!==undefined&&arg6!==undefined)
appboyUser[funcName](arg5,arg6);if(arg7!==undefined&&arg8!==undefined)
appboyUser[funcName](arg7,arg8);}else{appboyUser[funcName](u.data.user[funcName]);}}}
if(appboy.isPushPermissionGranted()){appboy.registerAppboyPushMessages();}
utag.DB("send:39:CALLBACK:COMPLETE");};u.callBack=function(){var data={};u.initialized=true;appboy.enabled=true
while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":"utag_39","attrs":{}});}}
utag.DB("send:39:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("39","chotot.chotot"));}catch(error){utag.DB(error);}
